exports.GENDERS_ENUM = {
  FEMALE: 'female',
  MALE: 'male',
  ALL: 'male,female',
};

exports.COLORS_ENUM = {
  BLACK: 'Black',
  WHITE: 'White',
  GRAY: 'Gray',
  TABBY: 'Tabby',
  ORANGE: 'Orange',
  CALICO: 'Calico',
  TUXEDO: 'Tuxedo',
  SIAMESE: 'Siamese',
  TORBIE: 'Torbie',
  BROWN: 'Brown',
  CREAM: 'Cream',
  BLUE: 'Blue',
  LILAC: 'Lilac',
  FAWN: 'Fawn',
  SILVER: 'Silver',
  CINNAMON: 'Cinnamon',
  CHOCOLATE: 'Chocolate',
  LYNX: 'Lynx',
  SMOKE: 'Smoke',
  BICOLOR: 'Bicolor',
  TORTOISESHELL: 'Tortoiseshell',

  ALL: 'Black,White,Gray,Tabby,Orange,Calico,Tuxedo,Siamese,Torbie,Brown,Cream,Blue,Lilac,Fawn,Silver,Cinnamon,Chocolate,Lynx,Smoke,Bicolor,Tortoiseshell',
};
// ALL: [
//   'Black',
//   'White',
//   'Gray',
//   'Tabby',
//   'Orange',
//   'Calico',
//   'Tuxedo',
//   'Siamese',
//   'Torbie',
//   'Brown',
//   'Cream',
//   'Blue',
//   'Lilac',
//   'Fawn',
//   'Silver',
//   'Cinnamon',
//   'Chocolate',
//   'Lynx',
//   'Smoke',
//   'Bicolor',
// ],

exports.CITY_ENUM = {
  VINNYTSIA: 'Vinnytsia',
  VOLYN: 'Volyn',
  DNIPROPETROVSK: 'Dnipropetrovsk',
  DONETSK: 'Donetsk',
  ZHYTOMYR: 'Zhytomyr',
  ZAKARPATTIA: 'Zakarpattia',
  ZAPORIZHZHIA: 'Zaporizhzhia',
  IVANOFRANKIVSK: 'Ivano-Frankivsk',
  KYIV: 'Kyiv',
  KIROVOHRAD: 'Kirovohrad',
  LUHANSK: 'Luhansk',
  LVIV: 'Lviv',
  MYKOLAIV: 'Mykolaiv',
  ODESSA: 'Odessa',
  POLTAVA: 'Poltava',
  RIVNE: 'Rivne',
  SUMY: 'Sumy',
  TERNOPIL: 'Ternopil',
  KHARKIV: 'Kharkiv',
  KHERSON: 'Kherson',
  KHMELNYTSKYI: 'Khmelnytskyi',
  CHERKASY: 'Cherkasy',
  CHERNIHIV: 'Chernihiv',
  CHERNIVTSI: 'Chernivtsi',

  ALL: 'Vinnytsia,Volyn,Dnipropetrovsk,Donetsk,Zhytomyr,Zakarpattia,Zaporizhzhia,Ivano-Frankivsk,Kyiv,Kirovohrad,Luhansk,Lviv,Mykolaiv,Odessa,Poltava,Rivne,Sumy,Ternopil,Kharkiv,Kherson,Khmelnytskyi,Cherkasy,Chernihiv,Chernivtsi',
};
// ALL: [
//   'Vinnytsia',
//   'Volyn',
//   'Dnipropetrovsk',
//   'Donetsk',
//   'Zhytomyr',
//   'Zakarpattia',
//   'Zaporizhzhia',
//   'Ivano-Frankivsk',
//   'Kyiv',
//   'Kirovohrad',
//   'Luhansk',
//   'Lviv',
//   'Mykolaiv',
//   'Odessa',
//   'Poltava',
//   'Rivne',
//   'Sumy',
//   'Ternopil',
//   'Kharkiv',
//   'Kherson',
//   'Khmelnytskyi',
//   'Cherkasy',
//   'Chernihiv',
//   'Chernivtsi',
// ],

exports.STATUS_ENUM = {
  DOMESTICATED: 'domesticated',
  HOMELESS: 'homeless',
  ALL: 'domesticated,homeless',
};
